### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tkusukawa/kusu#58]
```
Hi,Kusu

I've translate the plugin into Simplified Chinese.

Please check the attachment file. Thanks.

####################################################################
zh:
  work_time: "工时日志"
  wt_update: "更新"
  wt_month_names: "一月,二月,三月,四月,五月,六月,七月,八月,九月,十月,十一月,十二月"
  wt_week_day_names: "周日,周一,周二,周三,周四,周五,周六"
  wt_monthly_report: "月度报告"
  wt_daily_report: "日报告"
  wt_each_member_report: "成员报告"
  wt_raw_total: "月度报告(not relayed)"
  wt_edit_relay: "Ticket Relay 编辑器"
  wt_relay_total: "Tikect Relayed 月度报告"
  wt_ticket: "Ticket"
  wt_add_ticket: "新增ticket"
  wt_no_permission: "无权限"
  wt_loop_relay: "Ticket relation looped"
  wt_set_holiday: "设置当前日期为假期"
  wt_del_holiday: "设置当期日期为工作日"
  wt_apply_checked: "应用所有已选项"
  wt_select_project: "选择项目..."
  wt_select_user: "选择用户..."
  wt_edit_memo: "编辑备忘录"
  wt_pre_memo: "前一备忘录"
  wt_next_memo: "后一备忘录"
  wt_data_list: "数据清单"
  wt_input_ticket_numbers: "或输入问题编号"
  wt_delete_closed_tickets: "删除已关闭的Tickets"
####################################################################

```

Original issue reported on code.google.com by `archonwa...@gmail.com` on 29 Sep 2011 at 1:06
